# Generated by Django 3.1.5 on 2021-01-05 15:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('input_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('output_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_time_limit', models.FloatField(default=2.0)),
                ('problem_input', models.FileField(blank=True, upload_to='problemsdata/inputdata')),
                ('problem_output', models.FileField(blank=True, upload_to='problemsdata/outputdata')),
                ('total_solve', models.IntegerField(default=0)),
                ('total_submit', models.IntegerField(default=0)),
                ('special_judge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_result', models.CharField(default='Submitted', max_length=50)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(upload_to='problemsdata/submissiondata/')),
                ('language', models.CharField(max_length=50)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problemset')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
