# Generated by Django 3.1.5 on 2021-01-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_submission_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='token_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
