# Generated by Django 3.1.5 on 2021-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20210119_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='problem_input',
            field=models.FileField(blank=True, upload_to='static/problemsdata/inputdata'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='problem_output',
            field=models.FileField(blank=True, upload_to='static/problemsdata/outputdata'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uploaded_file',
            field=models.FileField(upload_to='static/problemsdata/submissiondata/'),
        ),
    ]
