# Generated by Django 3.1.5 on 2021-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20210126_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='problem_input',
            field=models.FileField(blank=True, upload_to='problemsdata/inputdata/'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='problem_output',
            field=models.FileField(blank=True, upload_to='problemsdata/outputdata/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uploaded_file',
            field=models.FileField(upload_to='problemsdata/submissiondata/'),
        ),
    ]
