# Generated by Django 3.1.5 on 2021-01-22 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0004_auto_20210119_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='clearifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declare_time', models.DateTimeField(auto_now_add=True)),
                ('clearification_text', models.TextField(max_length=1000)),
                ('judge_ignored', models.BooleanField(default=False)),
                ('judge_answer', models.TextField(blank=True, default='', max_length=4000)),
                ('associated_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('associated_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest_problemset')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='clearifications_viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clearifications_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearification.clearifications')),
            ],
        ),
    ]
