# Generated by Django 3.1.5 on 2021-01-16 17:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='contest_problemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=5)),
                ('problem_name', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('input_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('output_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('problem_time_limit', models.FloatField(default=2.0)),
                ('problem_input', models.FileField(blank=True, upload_to='contestData/problemset_input/')),
                ('problem_out', models.FileField(blank=True, upload_to='contestData/problemset_output/')),
                ('total_submit', models.IntegerField(default=0)),
                ('total_solve', models.IntegerField(default=0)),
                ('special_judge', models.BooleanField(default=False)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
            ],
        ),
        migrations.CreateModel(
            name='contestant_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField(default=0)),
                ('solve', models.IntegerField(default=0)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contest_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, null=True)),
                ('judge_result', models.CharField(default='Submitted', max_length=50)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(upload_to='contestData/user_submission/')),
                ('language', models.CharField(max_length=50)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest_problemset')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
