# Generated by Django 3.1.5 on 2021-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_problemset_problem_memory_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_problemset',
            name='sample_input',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contest_problemset',
            name='sample_output',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
