# Generated by Django 3.1.5 on 2021-01-19 17:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20210119_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_problemset',
            name='sample_input',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest_problemset',
            name='sample_output',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
