# Generated by Django 3.1.5 on 2021-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_upsolve_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
    ]
