# Generated by Django 3.1.5 on 2021-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20210124_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
