# Generated by Django 3.1.5 on 2021-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_auto_20210126_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_problemset',
            name='problem_input',
            field=models.FileField(blank=True, upload_to='static/contestData/problemset_input/'),
        ),
        migrations.AlterField(
            model_name='contest_problemset',
            name='problem_out',
            field=models.FileField(blank=True, upload_to='static/contestData/problemset_output/'),
        ),
        migrations.AlterField(
            model_name='contest_submission',
            name='uploaded_file',
            field=models.FileField(upload_to='static/contestData/user_submission/'),
        ),
        migrations.AlterField(
            model_name='contest_upsolve_submission',
            name='uploaded_file',
            field=models.FileField(upload_to='static/contestData/user_submission/'),
        ),
    ]
