# Generated by Django 3.1.5 on 2021-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20210126_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_problemset',
            name='problem_input',
            field=models.FileField(blank=True, upload_to='contestData/problemset_input/'),
        ),
        migrations.AlterField(
            model_name='contest_problemset',
            name='problem_out',
            field=models.FileField(blank=True, upload_to='contestData/problemset_output/'),
        ),
        migrations.AlterField(
            model_name='contest_submission',
            name='uploaded_file',
            field=models.FileField(upload_to='contestData/user_submission/'),
        ),
        migrations.AlterField(
            model_name='contest_upsolve_submission',
            name='uploaded_file',
            field=models.FileField(upload_to='contestData/user_submission/'),
        ),
    ]
