# Generated by Django 3.1.5 on 2021-01-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210116_0615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
