# Generated by Django 3.1.5 on 2021-01-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210116_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='institute_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
