# Generated by Django 3.1.5 on 2021-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210124_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
